spring:
  flyway:
    enabled: false
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/candidatos
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifeTime: 60000000
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8888
  error:
    include-message: always
    include-binding-errors: on-param
file-root-path: uploads